version: '2'

services:
  log-service1:
    image: nontoa10/log-service:latest
    container_name: log-service1
    ports:
      - "8081:9292"
    links:
      - "db:database"

  log-service2:
    image: nontoa10/log-service:latest
    container_name: log-service2
    ports:
      - "8082:9292"
    links:
      - "db:database"

  log-service3:
    image: nontoa10/log-service:latest
    container_name: log-service3
    ports:
      - "8083:9292"
    links:
      - "db:database"

  db:
    image: mongo:latest
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config: